# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title internal Correlation Matrix Correction
#'
#' @description
#' This function changes the order in which data is organized in order
#' to force the correlation matrix to a prescribed value. This implementation
#' uses the Hungtington-Lyrintzis algorithm.
#'
#' @name corcorr
#'
#' @param vars mat. WIP LHS matrix.
#' @param cor mat. Correlation matrix.
#' @param l int. Convergence tolerance.
#' @param FLAGSTOP int. Flag to check convergence .
#'
#' @return Void with outputs files written in the defined folder.
#'
#' @export
corcorr <- function(vars, cor, l, FLAGSTOP) {
    .Call('_trollcalibr_corcorr', PACKAGE = 'trollcalibr', vars, cor, l, FLAGSTOP)
}

